theme: jekyll-theme-leap-day
theme: jekyll-theme-cayman
description: "RESOURCEs and representations For Under-resourced Languages and domains"
basepath: "resourceful-2020/"

navigation:
- text: Home
  url: /index.html
- text: Schedule
  url: /schedule.html
- text: Invited Speakers
  url: /invited_speakers.html

